export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const SELECT_TODO = "SELECT_TODO";

export const TOGGLE_ADD_MODAL = "TOGGLE_ADD_MODAL";
export const TOGGLE_EDIT_MODAL = "TOGGLE_EDIT_MODAL";
export const TOGGLE_DELETE_MODAL = "TOGGLE_DELETE_MODAL";
export const VALIDATION_ADD_MODAL = "VALIDATION_ADD_MODAL";
export const VALIDATION_EDIT_MODAL = "VALIDATION_EDIT_MODAL";

export const ACTIVATE_TABLE_ROW = "ACTIVATE_TABLE_ROW";

export const VALIDATION = "VALIDATION";
export const ATTEMPT = "ATTEMPT";

export const SET_DATABASE_DATA = "SET_DATABASE_DATA";
